version: '3.7'

services:
  nifi_v2:
    image: nifi_2_0_0_m1
    container_name: nifi_2_0_0_m1
    restart: unless-stopped
    ports:
      - '8443:8443'
    env_file:
      - nifi.env
    volumes:
      - ./nifi_interno/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi_interno/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi_interno/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi_interno/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi_interno/state:/opt/nifi/nifi-current/state
      - ./nifi_interno/logs:/opt/nifi/nifi-current/logs
      - ./nifi_interno/conf:/opt/nifi/nifi-current/conf
      - ./certif:/opt/nifi/nifi-current/certif
      - ./dados_externos:/dados_externos
